export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const SET_AMAZON_PRODUCT = "SET_AMAZON_PRODUCT";
export const SET_BESTBUY_PRODUCT = "SET_BESTBUY_PRODUCT";
export const UPDATE_RESULT_LIST = "UPDATE_RESULT_LIST";
export const TRACK_PRODUCT = "TRACK_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_DASHBOARD_LIST = "UPDATE_DASHBOARD_LIST";
export const LOADING = "LOADING";